require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.2
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'spec/smoke_tests/**/*.rb'

# See https://github.com/rubocop-hq/rubocop/issues/6410
Layout/AlignHash:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - rubocop-rspec.gemspec
    - Rakefile
    - '**/*.rake'
    - spec/**/*.rb

Naming/FileName:
  Exclude:
    - lib/rubocop-rspec.rb

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/BooleanSymbol:
  Exclude:
    - lib/rubocop/cop/rspec/expect_actual.rb
    - lib/rubocop/cop/rspec/focus.rb

Lint/InterpolationCheck:
  Exclude:
    - spec/**/*.rb

RSpec/ExampleLength:
  Max: 30

RSpec/DescribeClass:
  Exclude:
    - spec/project/**/*.rb
