Style/FileName:
  Exclude:
    - lib/rubocop-rspec.rb

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

RSpec/ExampleLength:
  Max: 19
