require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.1

Metrics/BlockLength:
  Exclude:
    - rubocop-rspec.gemspec
    - Rakefile
    - '**/*.rake'
    - spec/**/*.rb

Naming/FileName:
  Exclude:
    - lib/rubocop-rspec.rb

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/BooleanSymbol:
  Exclude:
    - lib/rubocop/cop/rspec/expect_actual.rb
    - lib/rubocop/cop/rspec/focus.rb

Lint/InterpolationCheck:
  Exclude:
    - spec/**/*.rb

RSpec/ExampleLength:
  Max: 19

RSpec/DescribeClass:
  Exclude:
    - spec/project/**/*.rb
