name: CodeSpell
on:
  - pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  codespell:
    name: CodeSpell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: CodeSpell
        uses: codespell-project/actions-codespell@2b9806f41af12bec53e4f85ec5ac993fb4649c6d
        with:
          check_filenames: true
          check_hidden: true
          ignore_words_file: .codespellignore
