name: Publish
on:
  push:
    branches: master
    paths: lib/rubocop/rspec/version.rb
jobs:
  publish:
    name: Publish to RubyGems
    runs-on: ubuntu-latest
    if: github.repository_owner == 'rubocop'
    permissions:
      actions: write
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Set up Ruby
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1
        with:
          bundler-cache: true
          ruby-version: ruby
      - uses: rubygems/release-gem@052cc82692552de3ef2b81fd670e41d13cba8092 # v1
      - name: Create a GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          bundle exec rake create_release_notes
          gh release create $(git tag --points-at @) \
            --title "RuboCop RSpec $(git tag --points-at @)" \
            --notes-file relnotes.md
      - name: Replace version in Antora config
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          sed -i 's/version:.*$/version: ~/' docs/antora.yml
          if ! git diff --exit-code docs/antora.yml; then
            branch=switch-docs-version-$(git tag --points-at @)
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git checkout -b "$branch"
            git add docs/antora.yml
            git commit -m "Switch docs version back"
            git push -u origin "$branch"
            gh pr create --fill --head "$branch"
          fi
